[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "http://corsit.in/*"
  to = "https://www.corsit.in/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://corsit.in/*"
  to = "https://www.corsit.in/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"